#!/usr/bin/env python3
"""
Module for asynchronously comprehending
over the async_generator.
"""

import asyncio
from typing import List
from .0-async_generator import async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronous comprehension over
    the async_generator coroutine.

    Returns:
        List[float]: The list of 10 random numbers
        generated by the async_generator coroutine.
    """
    return [i async for i in async_generator()]
